feature: add flag UseDB1CLI on ImproveProject method
db1group/dgs-healthpanel-backend pull request #38
Opened 2023-12-19 12:44 UTC by rodolphostoppan

2023-12-19 12:56 UTC, erickantslima requested changes

2023-12-19 13:55 UTC, rodolphostoppan commented on Models/Requests/ProjectRequest.cs
fiz essa quebra só pra deixar no padrão do arquivo
seria melhor remover as quebras de linhas entre as propriedades?

2023-12-19 13:56 UTC, erickantslima commented on Models/Requests/ProjectRequest.cs
Não precisa quebrar, as propriedades podem ficar juntas sem problemas nesse projeto

2023-12-19 14:03 UTC, rodolphostoppan commented on Models/Requests/ProjectRequest.cs
ajustado

2024-01-19 14:27 UTC, erickantslima approved these changes

2024-01-22 12:35 UTC, merged